

transmitters:
  - private_key: ""
    address: "..."
  # - private_key: "..." 
  #   address: "..."     
  # - private_key: "..." 
  #   address: "..."     

receivers:
  - address: "..."
  # - address: "..."
  # - address: "..."

transaction_amount: 10000000