transmitter_private_key: "2Fv84CzbN54ikTEu1XjnDJ3P9habGgR5j3xHHVp8TsFaeEMMsggdmY5NhoQNw5dyNMWHeUvimVm1dMVwHhyCj1Vo"
transmitter_address: "8UsTkupEk2EpfTjW93LqZi2wMq3Yn3LqY78Yu5mh3mFT"
receiver_address: "83astBRguLMdt2h5U1Tpdq5tjFoJ6noeGwaY3mDLVcri"
transfer_amount: 1000000